"""paper_puppin2020 -- claims and deductions from Puppin et al. 2020.

Source: Evidence of Large Polarons in Photoemission Band Mapping of the Perovskite Semiconductor CsPbBr3
DOI: 10.1103/physrevlett.124.206402
Reference key: Puppin2020
"""
from gaia.lang import claim, deduction

# Claims first appearing in this paper. Leaf priors live in priors.py.

gcn_1544d55444d743c8 = claim(
    "The momentum-resolved valence-band dispersion of single-crystalline orthorhombic CsPbBr$_3$ at room temperature was measured by angle-resolved photoelectron spectroscopy (ARPES); here the measured quasiparticle energy as a function of the in-plane crystal momentum was fitted near the valence-band maximum (VBM) by the isotropic in-plane parabolic dispersion E(k)=E_{\\\\mathrm{VBM}}+\\\\hbar^{2}k^{2}/(2m_{\\\\mathrm{exp}}), where k is the magnitude of the two-dimensional in-plane wave vector (units Å^{-1}), \\\\hbar is the reduced Planck constant, and m_e is the free electron mass, and the energy zero was set at the VBM defined as the energy of the maximum of the energy-distribution curve (EDC) at the band top; this fit, performed on the upper valence band along the surface high-symmetry direction labeled \\\\bar{\\\\Gamma}-\\\\bar{M}, returns an experimental hole effective mass m_{\\\\mathrm{exp}}=0.26\\\\pm0.02\\\\,m_e. [@Puppin2020]",
    title="ARPES mass 0.26 in CsPbBr3",
    lkm_id="gcn_1544d55444d743c8",
    lkm_original="The momentum-resolved valence-band dispersion of single-crystalline orthorhombic CsPbBr$_3$ at room temperature was measured by angle-resolved photoelectron spectroscopy (ARPES); here the measured quasiparticle energy as a function of the in-plane crystal momentum was fitted near the valence-band maximum (VBM) by the isotropic in-plane parabolic dispersion E(k)=E_{\\\\mathrm{VBM}}+\\\\hbar^{2}k^{2}/(2m_{\\\\mathrm{exp}}), where k is the magnitude of the two-dimensional in-plane wave vector (units Å^{-1}), \\\\hbar is the reduced Planck constant, and m_e is the free electron mass, and the energy zero was set at the VBM defined as the energy of the maximum of the energy-distribution curve (EDC) at the band top; this fit, performed on the upper valence band along the surface high-symmetry direction labeled \\\\bar{\\\\Gamma}-\\\\bar{M}, returns an experimental hole effective mass m_{\\\\mathrm{exp}}=0.26\\\\pm0.02\\\\,m_e.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)

gcn_2e9e6e30a5d7431c = claim(
    "In an ARPES measurement of a crystalline semiconductor, let E(k) denote the measured quasiparticle energy as a function of the in-plane crystal momentum k (the magnitude of a two-dimensional wave vector measured in reciprocal angstroms, Å^{-1}), and let E_{\\\\mathrm{VBM}} denote the valence-band-maximum (VBM) energy defined as the highest occupied quasiparticle energy; within the momentum window used for fitting the upper valence band, taken here to be the region |k-k_{\\\\mathrm{VBM}}|\\\\lesssim0.1\\\\ \\\\text{\\\\AA}^{-1} around the momentum of the VBM, the quasiparticle dispersion is assumed to be well described by the isotropic in-plane parabolic form\n      E(k)=E_{\\\\mathrm{VBM}}+\\\\frac{\\\\hbar^{2}k^{2}}{2m_{\\\\mathrm{exp}}},\n      where \\\\hbar is the reduced Planck constant and m_{\\\\mathrm{exp}} is the fitted experimental hole effective mass; under this parabolic-band approximation, least-squares fitting of the experimentally extracted band maxima to this functional form returns m_{\\\\mathrm{exp}} and the systematic error in m_{\\\\mathrm{exp}} arising from neglected higher-order (nonparabolic) terms is smaller than the quoted experimental uncertainty of \\\\pm0.02\\\\,m_e, with m_e the free electron mass. [@Puppin2020]",
    title="Parabolic ARPES mass fit assumption",
    lkm_id="gcn_2e9e6e30a5d7431c",
    lkm_original="In an ARPES measurement of a crystalline semiconductor, let E(k) denote the measured quasiparticle energy as a function of the in-plane crystal momentum k (the magnitude of a two-dimensional wave vector measured in reciprocal angstroms, Å^{-1}), and let E_{\\\\mathrm{VBM}} denote the valence-band-maximum (VBM) energy defined as the highest occupied quasiparticle energy; within the momentum window used for fitting the upper valence band, taken here to be the region |k-k_{\\\\mathrm{VBM}}|\\\\lesssim0.1\\\\ \\\\text{\\\\AA}^{-1} around the momentum of the VBM, the quasiparticle dispersion is assumed to be well described by the isotropic in-plane parabolic form\n      E(k)=E_{\\\\mathrm{VBM}}+\\\\frac{\\\\hbar^{2}k^{2}}{2m_{\\\\mathrm{exp}}},\n      where \\\\hbar is the reduced Planck constant and m_{\\\\mathrm{exp}} is the fitted experimental hole effective mass; under this parabolic-band approximation, least-squares fitting of the experimentally extracted band maxima to this functional form returns m_{\\\\mathrm{exp}} and the systematic error in m_{\\\\mathrm{exp}} arising from neglected higher-order (nonparabolic) terms is smaller than the quoted experimental uncertainty of \\\\pm0.02\\\\,m_e, with m_e the free electron mass.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)

gcn_0a71cf6357114b76 = claim(
    "Let an energy-distribution curve (EDC) be the ARPES-measured photoemission intensity as a function of binding energy E at fixed parallel momentum k; the energy position of the maximum of the measured EDC at the band top is used to define the valence-band-maximum energy E_{\\\\mathrm{VBM}} for the purposes of setting the energy zero and extracting an effective mass, and any systematic shift of the EDC peak maximum from the true quasiparticle band-edge caused by many-body interactions, inelastic background, or the instrumental lineshape is assumed to be smaller than the quoted energy/mass uncertainty so that using the EDC peak maximum to set E=0 does not induce a systematic error larger than \\\\pm0.02\\\\,m_e in the fitted hole effective mass. [@Puppin2020]",
    title="EDC peak defines VBM energy",
    lkm_id="gcn_0a71cf6357114b76",
    lkm_original="Let an energy-distribution curve (EDC) be the ARPES-measured photoemission intensity as a function of binding energy E at fixed parallel momentum k; the energy position of the maximum of the measured EDC at the band top is used to define the valence-band-maximum energy E_{\\\\mathrm{VBM}} for the purposes of setting the energy zero and extracting an effective mass, and any systematic shift of the EDC peak maximum from the true quasiparticle band-edge caused by many-body interactions, inelastic background, or the instrumental lineshape is assumed to be smaller than the quoted energy/mass uncertainty so that using the EDC peak maximum to set E=0 does not induce a systematic error larger than \\\\pm0.02\\\\,m_e in the fitted hole effective mass.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)

gcn_e24a3d64aa604555 = claim(
    "ARPES intensity maps measured over in-plane momentum (k_x,k_y) and as a function of photon energy (which probes different values of the momentum component perpendicular to the surface, k_{\\\\perp}) together with band-unfolding calculations show that the observed periodicity of four valence-band maxima at the surface Brillouin-zone corners and the absence of an additional valence-band maximum at the surface \\\\bar{\\\\Gamma} point are not caused by surface reconstruction, k_{\\\\perp} dispersion, or matrix-element effects; specifically, energy- and polarization-dependent ARPES measurements reveal no signature of an additional VBM at \\\\bar{\\\\Gamma}, and unfolding of orthorhombic bands onto the cubic cell shows negligible spectral weight transfer to backfolded bands, so that the measured dispersion used to obtain m_{\\\\mathrm{exp}} represents bulk-like valence-band behavior relevant to the orthorhombic structure. [@Puppin2020]",
    title="ARPES dispersion is bulk-like",
    lkm_id="gcn_e24a3d64aa604555",
    lkm_original="ARPES intensity maps measured over in-plane momentum (k_x,k_y) and as a function of photon energy (which probes different values of the momentum component perpendicular to the surface, k_{\\\\perp}) together with band-unfolding calculations show that the observed periodicity of four valence-band maxima at the surface Brillouin-zone corners and the absence of an additional valence-band maximum at the surface \\\\bar{\\\\Gamma} point are not caused by surface reconstruction, k_{\\\\perp} dispersion, or matrix-element effects; specifically, energy- and polarization-dependent ARPES measurements reveal no signature of an additional VBM at \\\\bar{\\\\Gamma}, and unfolding of orthorhombic bands onto the cubic cell shows negligible spectral weight transfer to backfolded bands, so that the measured dispersion used to obtain m_{\\\\mathrm{exp}} represents bulk-like valence-band behavior relevant to the orthorhombic structure.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)

# LKM chain backbone.
gfac_31bb841408184d5e = deduction(
    [gcn_2e9e6e30a5d7431c, gcn_0a71cf6357114b76, gcn_e24a3d64aa604555],
    gcn_1544d55444d743c8,
    reason="1. Define ARPES as angle-resolved photoelectron spectroscopy, and define $m_e$ as the free electron mass; state that the experiment measured the momentum-resolved valence-band dispersion of single-crystalline orthorhombic $CsPbBr_3$ at room temperature using ARPES with extreme-ultraviolet photons in the 20–40 eV range; note that samples were cleaved in situ under ultrahigh vacuum and measurements were performed at room temperature in the orthorhombic phase as confirmed by x-ray diffraction.\n[28,29]\n\n2. State that the valence-band photoemission intensity distribution was recorded as a function of energy $E$ and in-plane momentum wave vectors $k_x$ and $k_y$, and that the authors plotted cuts of this three-dimensional ARPES intensity to inspect the upper valence band dispersion along high-symmetry directions of the surface Brillouin zone.\nFig. 1(d)\n\n3. Define \"valence-band maximum\" (VBM) as the highest-energy point of the valence band and state that the authors set the energy zero at the VBM; specify that the VBM energy was determined from the energy of the photoemission peak maximum in energy distribution curves (EDCs).\nFig. 1(e)\n\n4. State that ARPES data along the surface-path $\\bar{\\Gamma}-\\bar{M}-\\bar{\\Gamma}$ were acquired and that the upper valence band dispersion in this direction was extracted by fitting the valence-band energy distribution curves with a Gaussian line shape to determine the band maxima as a function of parallel momentum; define the symbol $m_{\\mathrm{exp}}$ to denote the experimentally determined hole effective mass.\nFig. 3\n\n5. State that the authors fitted the experimentally extracted band maxima of the upper valence band with a parabolic dispersion around the band maximum (i.e., they assumed $E(k)=E_{\\mathrm{VBM}}+\\frac{\\hbar^{2}k^{2}}{2m_{\\mathrm{exp}}}$ in the vicinity of the VBM, where $k$ is the in-plane wave vector measured from the VBM and $\\hbar$ is the reduced Planck constant) and that the fit was performed on the upper valence band along the $\\bar{\\Gamma}-\\bar{M}$ direction.\nFig. 3\n\n6. Report the fitted numerical result: the parabolic fit around the valence-band maximum yields an experimental hole effective mass $m_{\\mathrm{exp}}=0.26\\pm0.02\\,m_e$, where the stated uncertainty $\\pm0.02\\,m_e$ reflects the fitting and experimental uncertainties described in the methods and Supplemental Material.\nFig. 3\n[30]",
    prior=0.95,
)
gcn_5e907da32c114d34 = claim(
    "The sequence consisting of (i) ab initio DFPT evaluation of long-wavelength phonons, Born charges, and dielectric response and computation of the long-wavelength Fröhlich vertex and its energy-resolved squared coupling density d(g^{2})/d\\\\omega to obtain the effective single-mode parameters \\\\tilde{g}_{\\\\mathrm{LO}}^{2} and \\\\hbar\\\\tilde{\\\\omega}_{\\\\mathrm{LO}}, and (ii) a Feynman-polaron calculation using the ab initio bare mass m_{0} and the Fröhlich parameter \\\\alpha computed from those inputs, reproduces the ARPES-measured hole effective mass m_{\\\\mathrm{exp}}=0.26\\\\pm0.02\\\\,m_e for orthorhombic CsPbBr$_3$ within experimental uncertainty; therefore this ab initio electron–phonon evaluation combined with a Feynman-polaron treatment is a viable predictive method to compute carrier effective masses in lead-halide perovskites when the Fröhlich mechanism dominates carrier dressing. [@Puppin2020]",
    title="Feynman polaron reproduces ARPES mass",
    lkm_id="gcn_5e907da32c114d34",
    lkm_original="The sequence consisting of (i) ab initio DFPT evaluation of long-wavelength phonons, Born charges, and dielectric response and computation of the long-wavelength Fröhlich vertex and its energy-resolved squared coupling density d(g^{2})/d\\\\omega to obtain the effective single-mode parameters \\\\tilde{g}_{\\\\mathrm{LO}}^{2} and \\\\hbar\\\\tilde{\\\\omega}_{\\\\mathrm{LO}}, and (ii) a Feynman-polaron calculation using the ab initio bare mass m_{0} and the Fröhlich parameter \\\\alpha computed from those inputs, reproduces the ARPES-measured hole effective mass m_{\\\\mathrm{exp}}=0.26\\\\pm0.02\\\\,m_e for orthorhombic CsPbBr$_3$ within experimental uncertainty; therefore this ab initio electron–phonon evaluation combined with a Feynman-polaron treatment is a viable predictive method to compute carrier effective masses in lead-halide perovskites when the Fröhlich mechanism dominates carrier dressing.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)
gcn_943f1f964b7a4374 = claim(
    "Define the computational workflow as the sequence: (A) compute ab initio phonons, Born effective charges, and dielectric response by density-functional perturbation theory (DFPT); (B) compute the ab initio long-wavelength Fröhlich electron–phonon vertex and its energy-resolved squared coupling density d(g^{2})/d\\\\omega; (C) reduce the multi-mode result to a single effective LO-like mode characterized by parameters (\\\\tilde{g}_{\\\\mathrm{LO}}^{2},\\\\hbar\\\\tilde{\\\\omega}_{\\\\mathrm{LO}}) and compute the Fröhlich coupling parameter \\\\alpha from these inputs and the bare mass m_0; and (D) use a Feynman-polaron calculation with the ab initio bare mass m_0 and the computed \\\\alpha to predict the polaron-renormalized mass m_{\\\\mathrm{pol}}; the proposition is that this same sequence of calculations and approximations will produce quantitatively accurate predictions of carrier effective masses across the broader family of inorganic and hybrid lead-halide perovskites (LHPs) when the Fröhlich mechanism dominates carrier dressing, i.e., the method is generally predictive for LHPs beyond the tested case of orthorhombic CsPbBr$_3$. [@Puppin2020]",
    title="Ab initio Fröhlich workflow assumption",
    lkm_id="gcn_943f1f964b7a4374",
    lkm_original="Define the computational workflow as the sequence: (A) compute ab initio phonons, Born effective charges, and dielectric response by density-functional perturbation theory (DFPT); (B) compute the ab initio long-wavelength Fröhlich electron–phonon vertex and its energy-resolved squared coupling density d(g^{2})/d\\\\omega; (C) reduce the multi-mode result to a single effective LO-like mode characterized by parameters (\\\\tilde{g}_{\\\\mathrm{LO}}^{2},\\\\hbar\\\\tilde{\\\\omega}_{\\\\mathrm{LO}}) and compute the Fröhlich coupling parameter \\\\alpha from these inputs and the bare mass m_0; and (D) use a Feynman-polaron calculation with the ab initio bare mass m_0 and the computed \\\\alpha to predict the polaron-renormalized mass m_{\\\\mathrm{pol}}; the proposition is that this same sequence of calculations and approximations will produce quantitatively accurate predictions of carrier effective masses across the broader family of inorganic and hybrid lead-halide perovskites (LHPs) when the Fröhlich mechanism dominates carrier dressing, i.e., the method is generally predictive for LHPs beyond the tested case of orthorhombic CsPbBr$_3$.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)
gfac_9f427fc1c9c64387 = deduction(
    [gcn_943f1f964b7a4374],
    gcn_5e907da32c114d34,
    reason="1. Treat Conclusions 6 and 1 as established starting points: the Feynman-polaron calculation (Conclusion 6) predicts a polaron-renormalized hole mass $m_{\\mathrm{pol}}=0.24\\,m_e$, and the ARPES experiment (Conclusion 1) measured $m_{\\mathrm{exp}}=0.26\\pm0.02\\,m_e$.\n\n2. Compare the two values and state that $m_{\\mathrm{pol}}=0.24\\,m_e$ falls within the experimental uncertainty range of $m_{\\mathrm{exp}}=0.26\\pm0.02\\,m_e$ (specifically, the lower bound of the experimental interval is $0.24\\,m_e$), indicating quantitative agreement between the ab initio electron–phonon plus Feynman-polaron prediction and the ARPES measurement.\nFig. 4(a)\n\n3. Formulate the validation claim made by the authors: the combination of (i) ab initio evaluation of the Fröhlich vertex and dielectric response, yielding $\\tilde{g}_{\\mathrm{LO}}^{2}$ and $\\hbar\\tilde{\\omega}_{\\mathrm{LO}}$, and (ii) a Feynman polaron calculation using the ab initio bare mass $m_{0}$ and the computed $\\alpha$, reproduces the experimentally measured hole effective mass in orthorhombic $CsPbBr_3$ within experimental uncertainty; therefore, the presented first-principles electron–phonon calculation plus Feynman-polaron treatment constitutes a viable predictive method to compute carrier effective masses in lead-halide perovskites, as the authors assert.\n[45]",
    prior=0.95,
)
gcn_ffcf3464e99c47ed = claim(
    "Applying the Feynman variational polaron-model weak-to-intermediate coupling expansion\n      m_{\\\\mathrm{pol}}=m_{0}\\\\left(1+\\\\frac{\\\\alpha}{6}+0.025\\\\alpha^{2}+\\\\cdots\\\\right),\n      with the inputs m_{0}=0.17\\\\,m_e and \\\\alpha=1.81 produces a polaron-renormalized hole mass m_{\\\\mathrm{pol}}=0.24\\\\,m_e; this theoretical mass renormalization reduces the discrepancy between the computed bare mass and the ARPES-derived mass to within the experimental uncertainty of \\\\pm0.02\\\\,m_e. [@Puppin2020]",
    title="Polaron mass calculation gives 0.24",
    lkm_id="gcn_ffcf3464e99c47ed",
    lkm_original="Applying the Feynman variational polaron-model weak-to-intermediate coupling expansion\n      m_{\\\\mathrm{pol}}=m_{0}\\\\left(1+\\\\frac{\\\\alpha}{6}+0.025\\\\alpha^{2}+\\\\cdots\\\\right),\n      with the inputs m_{0}=0.17\\\\,m_e and \\\\alpha=1.81 produces a polaron-renormalized hole mass m_{\\\\mathrm{pol}}=0.24\\\\,m_e; this theoretical mass renormalization reduces the discrepancy between the computed bare mass and the ARPES-derived mass to within the experimental uncertainty of \\\\pm0.02\\\\,m_e.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)
gcn_2b322b6a88d742ba = claim(
    "For a Fröhlich polaron characterized by coupling strength \\\\alpha and bare electronic mass m_0, the Feynman variational polaron-model weak-to-intermediate coupling expansion\n      m_{\\\\mathrm{pol}}=m_0\\\\left(1+\\\\frac{\\\\alpha}{6}+0.025\\\\alpha^{2}+\\\\cdots\\\\right)\n      truncated at the displayed second-order term provides a numerical estimate of the polaron-renormalized effective mass m_{\\\\mathrm{pol}} that is accurate for \\\\alpha\\\\approx1.81 within truncation and variational errors small compared to the experimental uncertainty of \\\\pm0.02\\\\,m_e used in the ARPES-derived mass comparison. [@Puppin2020]",
    title="Feynman mass formula is valid here",
    lkm_id="gcn_2b322b6a88d742ba",
    lkm_original="For a Fröhlich polaron characterized by coupling strength \\\\alpha and bare electronic mass m_0, the Feynman variational polaron-model weak-to-intermediate coupling expansion\n      m_{\\\\mathrm{pol}}=m_0\\\\left(1+\\\\frac{\\\\alpha}{6}+0.025\\\\alpha^{2}+\\\\cdots\\\\right)\n      truncated at the displayed second-order term provides a numerical estimate of the polaron-renormalized effective mass m_{\\\\mathrm{pol}} that is accurate for \\\\alpha\\\\approx1.81 within truncation and variational errors small compared to the experimental uncertainty of \\\\pm0.02\\\\,m_e used in the ARPES-derived mass comparison.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm",
)
gfac_c33c62750055451d = deduction(
    [gcn_2b322b6a88d742ba],
    gcn_ffcf3464e99c47ed,
    reason="1. Treat Conclusions 5 and 2 as established starting points: the Fröhlich coupling parameter is $\\alpha=1.81$ and the bare mass is $m_{0}=0.17\\,m_e$; define $m_{\\mathrm{pol}}$ as the polaron-renormalized effective mass.\n\n2. Present the Feynman variational polaron-model weak-to-intermediate coupling expansion quoted by the authors:\n$$\nm_{\\mathrm{pol}}=m_{0}\\left(1+\\frac{\\alpha}{6}+0.025\\alpha^{2}+\\cdots\\right),\n$$\nand define each symbol: $m_{\\mathrm{pol}}$ is the polaron mass, $m_{0}$ is the bare mass, and $\\alpha$ is the Fröhlich coupling parameter.\n[75,76]\n\n3. Evaluate the series to second order using the provided numerical inputs: compute $\\frac{\\alpha}{6}=\\frac{1.81}{6}\\approx 0.3017$ and compute $0.025\\alpha^{2}=0.025\\times(1.81)^{2}\\approx 0.0819$; sum $1+0.3017+0.0819\\approx 1.3836$; multiply by $m_{0}=0.17\\,m_e$ to obtain $m_{\\mathrm{pol}}\\approx 0.17\\times 1.3836\\ m_e\\approx 0.235\\ m_e$, which the authors report as $m_{\\mathrm{pol}}=0.24\\,m_e$ after rounding.\n\n4. Compare the Feynman-model result to experiment: state that the computed polaron-renormalized mass $m_{\\mathrm{pol}}=0.24\\,m_e$ brings the theoretical quasiparticle mass into quantitative agreement with the ARPES-derived value $m_{\\mathrm{exp}}=0.26\\pm0.02\\,m_e$, i.e., the theoretical value lies within the experimental uncertainty interval, and conclude that the Feynman-polaron prediction accounts for the observed mass renormalization.\nFig. 4(a)",
    prior=0.95,
)
gcn_4ad259a13be9454a = claim(
    "ARPES single-particle spectral-function measurements at finite experimental energy resolution produce a quasiparticle peak whose linewidth is determined by combined instrumental broadening, thermal disorder, and intrinsic many-body scattering; in CsPbBr$_3$ the relevant optical longitudinal-optical (LO) phonon energies are \\leq25\\ \\mathrm{meV} and phonon-replica satellites separated by these energies cannot be resolved because the experimental quasiparticle linewidth exceeds the mode energy separations, yet the ARPES-measured quasiparticle dispersion and the fitted increase in effective mass still faithfully reflect the quasiparticle mass renormalization due to electron–phonon interactions, so that extraction of an increased effective mass from the fitted dispersion constitutes a valid signature of polaronic mass dressing even in the absence of resolved replica peaks. [@Puppin2020]",
    title="ARPES mass as polaron signature",
    lkm_id="gcn_4ad259a13be9454a",
    lkm_original="ARPES single-particle spectral-function measurements at finite experimental energy resolution produce a quasiparticle peak whose linewidth is determined by combined instrumental broadening, thermal disorder, and intrinsic many-body scattering; in CsPbBr$_3$ the relevant optical longitudinal-optical (LO) phonon energies are \\leq25\\ \\mathrm{meV} and phonon-replica satellites separated by these energies cannot be resolved because the experimental quasiparticle linewidth exceeds the mode energy separations, yet the ARPES-measured quasiparticle dispersion and the fitted increase in effective mass still faithfully reflect the quasiparticle mass renormalization due to electron–phonon interactions, so that extraction of an increased effective mass from the fitted dispersion constitutes a valid signature of polaronic mass dressing even in the absence of resolved replica peaks.",
    source_paper="paper:812638467241541632",
    provenance_source="lkm_no_chain",
)
