"""priors.py -- leaf-claim priors for this package.

Generated by lkm-to-gaia. Every entry is TODO-marked for review.
"""
from .paper_puppin2020 import (
    gcn_0a71cf6357114b76,
    gcn_2b322b6a88d742ba,
    gcn_2e9e6e30a5d7431c,
    gcn_4ad259a13be9454a,
    gcn_943f1f964b7a4374,
    gcn_e24a3d64aa604555,
)
from .paper_zhao2025 import (
    gcn_00749f497c204b4c,
    gcn_1c2bf8f398f243f9,
    gcn_43c66f240368417e,
    gcn_82d0efc0c1024ec8,
    gcn_869be47d79c54464,
    gcn_c24c81b8a5fe413c,
)
from .paper_sajedi2022 import (
    gcn_1fc9a84fbc6e4a1b,
    gcn_3e860bd7f76e4767,
    gcn_5868b15c687043a9,
    gcn_ccc6a5bf10864de7,
    gcn_e17b013445234bfa,
    gcn_e808f6450bfc4207,
    gcn_ec768b9675814820,
)

PRIORS = {
    gcn_00749f497c204b4c: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_0a71cf6357114b76: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_1c2bf8f398f243f9: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_1fc9a84fbc6e4a1b: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_2b322b6a88d742ba: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_2e9e6e30a5d7431c: (0.82, "ARPES parabolic-fit assumption from LKM evidence chain; TODO:review"),
    gcn_3e860bd7f76e4767: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_43c66f240368417e: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_4ad259a13be9454a: (0.68, "no-chain LKM source claim from Puppin2020 match provenance; TODO:review"),
    gcn_5868b15c687043a9: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_82d0efc0c1024ec8: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_869be47d79c54464: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_943f1f964b7a4374: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_c24c81b8a5fe413c: (0.72, "methodological assumption or model-comparison premise from LKM chain; TODO:review"),
    gcn_ccc6a5bf10864de7: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_e17b013445234bfa: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_e24a3d64aa604555: (0.84, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_e808f6450bfc4207: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
    gcn_ec768b9675814820: (0.80, "LKM chain premise or source claim with clear provenance; TODO:review"),
}
